---
hashicorp_url: https://apt.releases.hashicorp.com
service_name: consul
my_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
consul_server_ips:
  - "{{ hostvars[groups.robcloud[0]].ansible_default_ipv4.address }}"
