---
- name: Creating nodeexporter user group
  group: name=nodeexporter state=present

- name: Creating nodeexporter user
  user:
    name: nodeexporter
    group: nodeexporter
    system: yes
    shell: "/sbin/nologin"
    comment: "nodeexporter nologin User"
    createhome: false
    state: present

- name: Download node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ nodeexporter_version }}/node_exporter-{{ nodeexporter_version }}.linux-{{ linux_architecture }}.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy node exporter binary to bin
  copy:
    src: "/tmp/node_exporter-{{ nodeexporter_version }}.linux-{{ linux_architecture }}/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: nodeexporter
    group: nodeexporter
    remote_src: yes
    mode: 0755
    
- name: Delete nodeexporter tmp folder
  file:
    path: "/tmp/node_exporter-{{ nodeexporter_version }}.linux-{{ linux_architecture }}"
    state: absent     
    
- name: Copy systemd init file
  template:
    src: ../templates/node_exporter.init.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Start node exporter service
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: Restart the node exporter service
  service:
    name: node_exporter
    state: restarted      

- name: Check if node exporter is accessible
  uri:
    url: http://localhost:9100/metrics
    method: GET
    status_code: 200