#!/usr/bin/env ansible-playbook
---
- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: "Install common packages"
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - tree
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: "Stay powered up when laptop stuff happens"
    become: yes
    lineinfile:
      path: /etc/systemd/logind.conf
      regexp: "{{ item }}="
      line: "{{ item }}=ignore"
    loop:
      - HandleLidSwitch
      - HandleLidSwitchExternalPower
      - HandlePowerKey

