#!/usr/bin/env ansible-playbook
---
- hosts: all:!pis

  tasks:
    - name: "Stop existing FAH containers"
      shell: docker stop folding-at-home

    - name: "Remove existing FAH containers"
      shell: docker rm folding-at-home

    - name: "Run FAH docker image"
      shell: docker run \
        -d \
        --name folding-at-home \
        -p 7396:7396 \
        -p 36330:36330 \
        -e USER=Anonymous \
        -e TEAM=0 \
        -e ENABLE_GPU=false \
        -e ENABLE_SMP=true \
        --restart unless-stopped \
        yurinnick/folding-at-home \
        --allow 0/0 \
        --command-allow-no-pass 10.0.0.0/24
