#!/usr/bin/env ansible-playbook
---
- hosts: robcloud
  become: true
  become_method: sudo

  tasks:
    - name: "Stop existing FAH containers"
      shell: docker stop folding-at-home || true && docker rm folding-at-home || true

    - name: "Run FAH docker image"
      shell: docker run \
        -d \
        --name folding-at-home \
        -p 7396:7396 \
        -p 36330:36330 \
        -e USER={{ inventory_hostname }} \
        -e TEAM=259198 \
        -e ENABLE_GPU=false \
        -e ENABLE_SMP=true \
        -e PASSKEY={{ passkey }}
        --restart unless-stopped \
        yurinnick/folding-at-home \
        --allow 10.0.0.0/16 \
        --web-allow 10.0.0.0/16 \
        --command-allow-no-pass 10.0.0.0/16 \
        --power=medium
