#!/usr/bin/env ansible-playbook
---
- hosts: robcloud
  become: true
  become_method: sudo

  vars:
    hashicorp_url: https://apt.releases.hashicorp.com

  tasks:
    - name: Official Hashicorp GPG key
      apt_key:
        url: "{{ hashicorp_url }}/gpg"
        state: present

    - name: Hashicorp APT repository
      apt_repository:
        repo: "deb [arch={{ apt_architecture }}] {{ hashicorp_url }} {{ ansible_distribution_release }} main"
        state: present 

    - name: "Update APT"
      apt:
        update_cache: yes