#!/usr/bin/env ansible-playbook
---
- hosts: all
  become: true
  become_method: sudo

  vars:
    nodeexporter_version: 0.18.1

  tasks:
  - name: Download node exporter
    unarchive:
      src: "https://github.com/prometheus/node_exporter/releases/download/v{{ nodeexporter_version }}/node_exporter-{{ nodeexporter_version }}.linux-{{ linux_architecture }}.tar.gz"
      dest: /tmp/
      remote_src: yes
  
  - name: Copy node exporter binary to bin
    copy:
      src: "/tmp/node_exporter-{{ nodeexporter_version }}.linux-{{ linux_architecture }}/node_exporter"
      dest: "/usr/local/bin/node_exporter"
      owner: prometheus
      group: prometheus
      remote_src: yes
      mode: 0755
      
  - name: Delete prometheus tmp folder
    file:
      path: "/tmp/node_exporter-{{ nodeexporter_version }}.linux-{{ linux_architecture }}"
      state: absent     
      
  - name: Copy systemd init file
    template:
      src: ../templates/node_exporter.init.service.j2
      dest: /etc/systemd/system/node_exporter.service
    notify: systemd_reload

  - name: Start node exporter service
    service:
      name: node_exporter
      state: started
      enabled: yes

  - name: Check if node exporter is accessible
    uri:
      url: http://localhost:9100/metrics
      method: GET
      status_code: 200
  
  handlers:
  - name: Restart the node exporter service
    service:
      name: node_exporter
      state: restarted
    listen: event_restart_node_exporter

  - name: Reload systemd
    command: systemctl daemon-reload
    listen: systemd_reload