#!/usr/bin/env ansible-playbook
---
- hosts: desktops,laptops
  become: true
  become_method: sudo
  roles:
    - role: base
    - role: laptops
      when: "'laptops' in group_names"
    - role: docker
    - role: node_exporter
