#!/usr/bin/env ansible-playbook
---
- hosts: all
  become: true
  become_method: sudo
  roles:
    - base
    - docker
    - node_exporter

- hosts: laptops
  become: true
  become_method: sudo
  roles:
    - laptops
