#!/usr/bin/env ansible-playbook
---
- hosts: robcloud
  become: true
  become_method: sudo

  roles:
    - role: base
    - role: laptops
      when: "'laptops' in group_names"
    - role: docker
    - role: consul
    - role: prometheus
    - role: node_exporter
