#!/usr/bin/env ansible-playbook
---
- hosts: n5.robcloud
  become: true
  become_method: sudo

  tasks:
  - name: "Bot directory"
    file:
      path: "/opt/vaccinebot"
      state: directory
      mode: 0755
      owner: rob
      group: rob

  - name: "Copying bot"
    copy:
      src: "../systems/vaccinebot/bot.sh"
      dest: "/opt/vaccinebot/bot.sh"
      mode: '0755'

  - name: "Copying Dockerfile"
    copy:
      src: "../systems/vaccinebot/Dockerfile"
      dest: "/opt/vaccinebot/Dockerfile"

  - name: "Build image"
    shell: 
      cmd: docker build -t vaccinebot .
      chdir: "/opt/vaccinebot"  

  - name: "Stop existing bot"
    shell: docker stop vaccinebot || true && docker rm vaccinebot || true 

  - name: "Run bot"
    shell: docker run \
        -d \
        --name vaccinebot \
        --restart unless-stopped \
        --network host \
        vaccinebot
